apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    app: {{.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      name: {{.Name}}
      labels:
        app: {{.Name}}
    spec:
      volumes:
        - name: {{.Name}}-storage
          persistentVolumeClaim:
            claimName: {{.Name}}-pvc
      containers:
        - name: {{.Name}}-engine
          image: traefik/whoami
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{.Port}}
          volumeMounts:
            - mountPath: "/app/data"
              name: {{.Name}}-storage
      initContainers:
        - name: {{.Name}}-init
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', 'wget -O game.jsdos -P /app/data --no-check-certificate https://architecture-center-jsdos-bundles.obs.eu-de.otc.t-systems.com/1179a7c9e05b1679333ed6db08e7884f6e86c155.jsdos' ]
          volumeMounts:
            - mountPath: "/app/data"
              name: {{.Name}}-storage
      restartPolicy: Always
      