apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    app: {{.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      name: {{.Name}}
      labels:
        app: {{.Name}}
    spec:
      volumes:
        - name: {{.Name}}-storage
          persistentVolumeClaim:
            claimName: {{.Name}}-pvc
      containers:
        - name: {{.Name}}-engine
          image: traefik/whoami
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{.Port}}
          volumeMounts:
            - mountPath: "/app/data"
              name: {{.Name}}-storage
      restartPolicy: Always
      