apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Name}}-pv
  namespace: {{.Namespace}}
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/{{.Namespace}}/{{.Name}}"